console.log('hi! I am not learning git')
console.log('this is feature commit 1')
console.log('this is yolo')
console.log('hehe')
console.log('master commit-1')
console.log('master commit-2')
console.log('feature-3 commit-1')
console.log('feature-3 commit-2')